### ISSUE TITLE
[Bug] Random Crash

### ISSUE THREAD

**Issue by NikunjKhangwal** [namidaco/namida#158]
The app randomly crashed for me. From what i remember:- i opened the app and tried to open sidebar while re-indexing was happening.
```
FATAL EXCEPTION: DefaultDispatcher-worker-1
Process: com.msob7y.namida, PID: 22549
java.io.IOException: Stream closed
	at java.io.BufferedWriter.ensureOpen(BufferedWriter.java:107)
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:117)
	at java.io.BufferedWriter.flush(BufferedWriter.java:256)
	at com.msob7y.namida.FAudioTagger$Companion._removeLogsUser(FAudioTagger.kt:73)
	at com.msob7y.namida.FAudioTagger$onMethodCall$2.invokeSuspend(FAudioTagger.kt:161)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b9580be, Dispatchers.IO]
```

**Comment by MSOB7YY** [comment]
dawg, it should be some kind of a rare case, will try to fix

**Comment by NikunjKhangwal** [comment]
Looks like a major one too. Already happened a lot of time while just navigating app.

![IMG_20240408_163643](https://github.com/namidaco/namida/assets/99175083/3a231136-da60-4920-86f4-4a467090853f)

**Comment by NikunjKhangwal** [comment]
> Crashes happen when you play m4a containing data in alac. Android doesn't support it, and Namida doesn't have a decoder for it.

As i mentioned these crashes happened even when something was not playing. Just normal navigating within app. Besides i dont use alac. Most of my audio files are aac with m4a container.

**Comment by MSOB7YY** [comment]
the error is related to tagger logs file, so the issue should happen only when indexing/refreshing (including if u enabled refresh on startup).
otherwise, pls share full logs

**Comment by NikunjKhangwal** [comment]
I indeed have refresh on startup enabled

**Comment by MSOB7YY** [comment]
this should be fixed in db055a403406454bca690daf2259e38e21ba5d99

**Comment by NikunjKhangwal** [comment]
Is this crash related?
```
FATAL EXCEPTION: main
Process: com.msob7y.namida, PID: 18364
java.lang.RuntimeException: Unable to stop service com.ryanheise.audioservice.AudioService@283b22: java.io.IOException: Stream closed
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4858)
	at android.app.ActivityThread.access$2300(ActivityThread.java:275)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2211)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8280)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
Caused by: java.io.IOException: Stream closed
	at java.io.BufferedWriter.ensureOpen(BufferedWriter.java:107)
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:117)
	at java.io.BufferedWriter.flush(BufferedWriter.java:256)
	at com.msob7y.namida.FAudioTagger.onDetachedFromEngine(FAudioTagger.kt:465)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:272)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:282)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:290)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:123)
	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:460)
	at com.ryanheise.audioservice.AudioServicePlugin.disposeFlutterEngine(AudioServicePlugin.java:111)
	at com.ryanheise.audioservice.AudioServicePlugin$AudioHandlerInterface.onDestroy(AudioServicePlugin.java:807)
	at com.ryanheise.audioservice.AudioService.onDestroy(AudioService.java:385)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4838)
	... 9 more
```

**Comment by MSOB7YY** [comment]
@NikunjKhangwal yeah it's the same one. are you on v2.0.9 beta? if so, can u send the logs

**Comment by NikunjKhangwal** [comment]
Naah, I'm on stable

**Comment by MSOB7YY** [comment]
@NikunjKhangwal oh alr, usually it should only happen with indexer related processes, and ofc fixed in beta
