### ISSUE TITLE
[Bug] Youtube comments aren't loading

### ISSUE THREAD

**Issue by NikunjKhangwal** [namidaco/namida#161]
Notice how the app tries to load comment but the section shows up and dissappears in a second

https://github.com/namidaco/namida/assets/99175083/a3154f45-b735-4a99-97ad-b18d55ba3cd1

**Comment by MSOB7YY** [comment]
might be an issue with the internal extractor, or a ui issue, can u try disable top comments in yt settings? does it happen for all videos? is there any comments cached in old videos u watched?

**Comment by NikunjKhangwal** [comment]
Weird. After turning on bottom ones, the comments showed for some time but the app tried to refresh them 3 times before finally getting it. Later the comments disappeared in bottom as well and got the message "error displaying comments". It happens for all videos and no i didn't had cached comments.

**Comment by NikunjKhangwal** [comment]
Also got this crash while testing. Not sure if it's related. Tell me if i need a seperate issue for it.

````
FATAL EXCEPTION: main
Process: com.msob7y.namida, PID: 4614
java.lang.RuntimeException: Unable to stop service com.ryanheise.audioservice.AudioService@2731cb5: java.io.IOException: Stream closed
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4858)
	at android.app.ActivityThread.access$2300(ActivityThread.java:275)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2211)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8280)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
Caused by: java.io.IOException: Stream closed
	at java.io.BufferedWriter.ensureOpen(BufferedWriter.java:107)
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:117)
	at java.io.BufferedWriter.flush(BufferedWriter.java:256)
	at com.msob7y.namida.FAudioTagger.onDetachedFromEngine(FAudioTagger.kt:465)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:272)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:282)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:290)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:123)
	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:460)
	at com.ryanheise.audioservice.AudioServicePlugin.disposeFlutterEngine(AudioServicePlugin.java:111)
	at com.ryanheise.audioservice.AudioServicePlugin$AudioHandlerInterface.onDestroy(AudioServicePlugin.java:807)
	at com.ryanheise.audioservice.AudioService.onDestroy(AudioService.java:385)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4838)
	... 9 more
````

**Comment by MSOB7YY** [comment]
no that's the same one as in #158, as for the comments i confirmed it's not working, totally an internal extractor issue (youtube changed stuff), will either try to update it or continue on my own extractor

**Comment by NikunjKhangwal** [comment]
No prob. I don't use YouTube part of app a lot. But i have this weird habit of checking out every new change in new updates of my apps. Hence i open a lot of issues at the same time. This one was found by accident.

**Comment by MSOB7YY** [comment]
fixed with the new client and is working fine [in beta](https://github.com/namidaco/namida-snapshots/releases), the login part is almost done too so the feed will work along with it, track it at #227
