### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by ArhnZd** [namidaco/namida#257]
## Question 
Are we able to import our spotify playlists to namida?

## Logs

LOG TXT FILE 1
```
{
  "#0      _evaluateBackgroundNotificationCallback (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:880)\n#1      AndroidFlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:138)\n#2      FlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:143)\n#3      NotificationService.init (package:namida/controller/notification_controller.dart:31)\n#4      new NotificationService._internal (package:namida/controller/notification_controller.dart:17)\n#5      NotificationService._notificationService (package:namida/controller/notification_controller.dart:9)\n#6      YoutubeController.renameConfigFilename (package:namida/youtube/controller/youtube_controller.dart)\n#7      YTDownloadTaskItemCard._onRenameIconTap.<anonymous closure> (package:namida/youtube/widgets/yt_download_task_item_card.dart:450)\n#8      showNamidaBottomSheetWithTextField.<anonymous closure>.<anonymous closure> (package:namida/core/functions.dart:705)\n#9      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1171)\n#10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344)\n#11     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652)\n#12     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309)\n#13     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279)\n#14     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167)\n#15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:499)\n#16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475)\n#17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:425)\n#18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420)\n#19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383)\n#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330)\n#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299)\n#22     _rootRunUnary (dart:async/zone.dart:1415)\n#23     _CustomZone.runUnary (dart:async/zone.dart:1308)\n#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)\n#25     _invoke1 (dart:ui/hooks.dart:330)\n#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442)\n#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)\n": {
    "Null check operator used on a null value => _TypeError": 1
  },
  "": {
    "PlatformException(abort, Connection aborted, null, null) => PlatformException": 2
  }
}

```
LOG TXT FILE 2
```
{
  "android": {
    "product": "CPH2381",
    "supportedAbis": [
      "arm64-v8a",
      "armeabi-v7a",
      "armeabi"
    ],
    "serialNumber": "unknown",
    "displayMetrics": {
      "xDpi": 403.4110107421875,
      "widthPx": 1080.0,
      "heightPx": 2412.0,
      "yDpi": 400.4230041503906
    },
    "display": "CPH2381_14.0.0.601(EX01)",
    "type": "user",
    "isPhysicalDevice": true,
    "version": {
      "baseOS": "",
      "securityPatch": "2024-05-05",
      "sdkInt": 34,
      "release": "14",
      "codename": "REL",
      "previewSdkInt": 0,
      "incremental": "S.17cd02c-44a3-1105b"
    },
    "manufacturer": "OnePlus",
    "tags": "release-keys",
    "bootloader": "unknown",
    "fingerprint": "OnePlus/CPH2381/OP535DL1:14/UKQ1.230924.001/S.17cd02c-44a3-1105b:user/release-keys",
    "host": "dg02-pool06-kvm25",
    "model": "CPH2381",
    "id": "UKQ1.230924.001",
    "brand": "OnePlus",
    "device": "OP535DL1",
    "board": "holi",
    "hardware": "qcom"
  },
  "package": {
    "appName": "Namida",
    "buildNumber": "240522118",
    "packageName": "com.msob7y.namida",
    "version": "2.5.6",
    "buildSignature": "1B5B89C720BF776B82CB332B1E7DC3AB15EAC8BF",
    "installerStore": "com.google.android.packageinstaller"
  }
}
===============================

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ Null check operator used on a null value
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   _evaluateBackgroundNotificationCallback (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:880)
│ #1   AndroidFlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:138)
│ #2   FlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:143)
│ #3   NotificationService.init (package:namida/controller/notification_controller.dart:31)
│ #4   new NotificationService._internal (package:namida/controller/notification_controller.dart:17)
│ #5   NotificationService._notificationService (package:namida/controller/notification_controller.dart:9)
│ #6   YoutubeController._doneDownloadingNotification (package:namida/youtube/controller/youtube_controller.dart)
│ #7   YoutubeController._downloadYoutubeVideoRaw (package:namida/youtube/controller/youtube_controller.dart:1532)
│ #8   <asynchronous suspension>
│ #9   YoutubeController.downloadYoutubeVideos.downloady (package:namida/youtube/controller/youtube_controller.dart:1163)
│ #10   <asynchronous suspension>
│ #11   YoutubeController.downloadYoutubeVideos.<anonymous closure> (package:namida/youtube/controller/youtube_controller.dart:1244)
│ #12   <asynchronous suspension>
│ #13   YoutubeController.downloadYoutubeVideos (package:namida/youtube/controller/youtube_controller.dart:1244)
│ #14   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ _TypeError
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ PlatformException(NoActivityException, dev.fluttercommunity.plus.wakelock.NoActivityException: wakelock requires a foreground activity, Cause: null, Stacktrace: dev.fluttercommunity.plus.wakelock.NoActivityException: wakelock requires a foreground activity
│ 	at dev.fluttercommunity.plus.wakelock.Wakelock.toggle(Wakelock.kt:17)
│ 	at dev.fluttercommunity.plus.wakelock.WakelockPlusPlugin.toggle(WakelockPlusPlugin.kt:42)
│ 	at WakelockPlusApi$Companion.setUp$lambda$1$lambda$0(Messages.g.kt:143)
│ 	at WakelockPlusApi$Companion.$r8$lambda$V3Ef3eoUCWaUg6-SG5-vgDNZXN8(Messages.g.kt:0)
│ 	at WakelockPlusApi$Companion$$ExternalSyntheticLambda0.onMessage(R8$$SyntheticClass:0)
│ 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
│ 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
│ 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:319)
│ 	at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$2j2MERcK825A5j1fv5sZ7xB2Iuo(DartMessenger.java:0)
│ 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
│ 	at android.os.Handler.handleCallback(Handler.java:958)
│ 	at android.os.Handler.dispatchMessage(Handler.java:99)
│ 	at android.os.Looper.loopOnce(Looper.java:257)
│ 	at android.os.Looper.loop(Looper.java:368)
│ 	at android.app.ActivityThread.main(ActivityThread.java:8819)
│ 	at java.lang.reflect.Method.invoke(Native Method)
│ 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
│ 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
│ , null)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   WakelockPlusApi.toggle (package:wakelock_plus_platform_interface/messages.g.dart:126)
│ #1   <asynchronous suspension>
│ #2   MethodChannelWakelockPlus.toggle (package:wakelock_plus_platform_interface/src/method_channel_wakelock_plus.dart:20)
│ #3   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ PlatformException
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ PlatformException(NoActivityException, dev.fluttercommunity.plus.wakelock.NoActivityException: wakelock requires a foreground activity, Cause: null, Stacktrace: dev.fluttercommunity.plus.wakelock.NoActivityException: wakelock requires a foreground activity
│ 	at dev.fluttercommunity.plus.wakelock.Wakelock.toggle(Wakelock.kt:17)
│ 	at dev.fluttercommunity.plus.wakelock.WakelockPlusPlugin.toggle(WakelockPlusPlugin.kt:42)
│ 	at WakelockPlusApi$Companion.setUp$lambda$1$lambda$0(Messages.g.kt:143)
│ 	at WakelockPlusApi$Companion.$r8$lambda$V3Ef3eoUCWaUg6-SG5-vgDNZXN8(Messages.g.kt:0)
│ 	at WakelockPlusApi$Companion$$ExternalSyntheticLambda0.onMessage(R8$$SyntheticClass:0)
│ 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
│ 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
│ 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:319)
│ 	at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$2j2MERcK825A5j1fv5sZ7xB2Iuo(DartMessenger.java:0)
│ 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
│ 	at android.os.Handler.handleCallback(Handler.java:958)
│ 	at android.os.Handler.dispatchMessage(Handler.java:99)
│ 	at android.os.Looper.loopOnce(Looper.java:257)
│ 	at android.os.Looper.loop(Looper.java:368)
│ 	at android.app.ActivityThread.main(ActivityThread.java:8819)
│ 	at java.lang.reflect.Method.invoke(Native Method)
│ 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
│ 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
│ , null)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   WakelockPlusApi.toggle (package:wakelock_plus_platform_interface/messages.g.dart:126)
│ #1   <asynchronous suspension>
│ #2   MethodChannelWakelockPlus.toggle (package:wakelock_plus_platform_interface/src/method_channel_wakelock_plus.dart:20)
│ #3   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ PlatformException
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ PlatformException(NoActivityException, dev.fluttercommunity.plus.wakelock.NoActivityException: wakelock requires a foreground activity, Cause: null, Stacktrace: dev.fluttercommunity.plus.wakelock.NoActivityException: wakelock requires a foreground activity
│ 	at dev.fluttercommunity.plus.wakelock.Wakelock.toggle(Wakelock.kt:17)
│ 	at dev.fluttercommunity.plus.wakelock.WakelockPlusPlugin.toggle(WakelockPlusPlugin.kt:42)
│ 	at WakelockPlusApi$Companion.setUp$lambda$1$lambda$0(Messages.g.kt:143)
│ 	at WakelockPlusApi$Companion.$r8$lambda$V3Ef3eoUCWaUg6-SG5-vgDNZXN8(Messages.g.kt:0)
│ 	at WakelockPlusApi$Companion$$ExternalSyntheticLambda0.onMessage(R8$$SyntheticClass:0)
│ 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
│ 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
│ 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:319)
│ 	at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$2j2MERcK825A5j1fv5sZ7xB2Iuo(DartMessenger.java:0)
│ 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
│ 	at android.os.Handler.handleCallback(Handler.java:958)
│ 	at android.os.Handler.dispatchMessage(Handler.java:99)
│ 	at android.os.Looper.loopOnce(Looper.java:257)
│ 	at android.os.Looper.loop(Looper.java:368)
│ 	at android.app.ActivityThread.main(ActivityThread.java:8819)
│ 	at java.lang.reflect.Method.invoke(Native Method)
│ 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
│ 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
│ , null)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   WakelockPlusApi.toggle (package:wakelock_plus_platform_interface/messages.g.dart:126)
│ #1   <asynchronous suspension>
│ #2   MethodChannelWakelockPlus.toggle (package:wakelock_plus_platform_interface/src/method_channel_wakelock_plus.dart:20)
│ #3   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ PlatformException
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ PlatformException(NoActivityException, dev.fluttercommunity.plus.wakelock.NoActivityException: wakelock requires a foreground activity, Cause: null, Stacktrace: dev.fluttercommunity.plus.wakelock.NoActivityException: wakelock requires a foreground activity
│ 	at dev.fluttercommunity.plus.wakelock.Wakelock.toggle(Wakelock.kt:17)
│ 	at dev.fluttercommunity.plus.wakelock.WakelockPlusPlugin.toggle(WakelockPlusPlugin.kt:42)
│ 	at WakelockPlusApi$Companion.setUp$lambda$1$lambda$0(Messages.g.kt:143)
│ 	at WakelockPlusApi$Companion.$r8$lambda$V3Ef3eoUCWaUg6-SG5-vgDNZXN8(Messages.g.kt:0)
│ 	at WakelockPlusApi$Companion$$ExternalSyntheticLambda0.onMessage(R8$$SyntheticClass:0)
│ 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
│ 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
│ 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:319)
│ 	at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$2j2MERcK825A5j1fv5sZ7xB2Iuo(DartMessenger.java:0)
│ 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
│ 	at android.os.Handler.handleCallback(Handler.java:958)
│ 	at android.os.Handler.dispatchMessage(Handler.java:99)
│ 	at android.os.Looper.loopOnce(Looper.java:257)
│ 	at android.os.Looper.loop(Looper.java:368)
│ 	at android.app.ActivityThread.main(ActivityThread.java:8819)
│ 	at java.lang.reflect.Method.invoke(Native Method)
│ 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
│ 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
│ , null)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   WakelockPlusApi.toggle (package:wakelock_plus_platform_interface/messages.g.dart:126)
│ #1   <asynchronous suspension>
│ #2   MethodChannelWakelockPlus.toggle (package:wakelock_plus_platform_interface/src/method_channel_wakelock_plus.dart:20)
│ #3   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ PlatformException
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ Null check operator used on a null value
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   _evaluateBackgroundNotificationCallback (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:880)
│ #1   AndroidFlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:138)
│ #2   FlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:143)
│ #3   NotificationService.init (package:namida/controller/notification_controller.dart:31)
│ #4   new NotificationService._internal (package:namida/controller/notification_controller.dart:17)
│ #5   NotificationService._notificationService (package:namida/controller/notification_controller.dart:9)
│ #6   YoutubeController.renameConfigFilename (package:namida/youtube/controller/youtube_controller.dart)
│ #7   YTDownloadTaskItemCard._onRenameIconTap.<anonymous closure> (package:namida/youtube/widgets/yt_download_task_item_card.dart:450)
│ #8   showNamidaBottomSheetWithTextField.<anonymous closure>.<anonymous closure> (package:namida/core/functions.dart:705)
│ #9   _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1171)
│ #10   GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344)
│ #11   TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652)
│ #12   BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309)
│ #13   BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279)
│ #14   GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167)
│ #15   GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:499)
│ #16   GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475)
│ #17   RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:425)
│ #18   GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420)
│ #19   GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383)
│ #20   GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330)
│ #21   GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299)
│ #22   _rootRunUnary (dart:async/zone.dart:1415)
│ #23   _CustomZone.runUnary (dart:async/zone.dart:1308)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ _TypeError
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ PlatformException(abort, Connection aborted, null, null)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ PlatformException
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ PlatformException(abort, Connection aborted, null, null)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ PlatformException
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
```

**Comment by MSOB7YY** [comment]
not possible. spotify content cannot even be played since its drm protected, so basically storing playlist will be pointless unless i were to implement a lookup/search to fetch content from yt/etc instead which im not gonna do now

although importing history could be possible (the same way lastfm history is imported), if u get ur listening record ill be happy to implement history import for spotify
