### ISSUE TITLE
[BUG] Error playing video, skipping:(0) Source error

### ISSUE THREAD

**Issue by minhmc2007** [namidaco/namida#298]
![Screenshot_20240725_175425](https://github.com/user-attachments/assets/d756769e-2114-4f52-b6c2-c33703228172)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by minhmc2007** [comment]
This is the log:
{
  "#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42)\n#1      _Directory.listSync (dart:io/directory_impl.dart:228)\n#2      _cleanOldLogs (package:namida/main.dart:194)\n#3      compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:19)\n#4      _RemoteRunner._run (dart:isolate:1090)\n#5      _RemoteRunner._remoteExecute (dart:isolate:1084)\n#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300)\n#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)\n": {
    "PathNotFoundException: Directory listing failed, path = '/storage/emulated/0/Android/data/com.msob7y.namida/files/Logs/' (OS Error: No such file or directory, errno = 2) => PathNotFoundException": 1
  },
  "#0      LockCachingAudioSource._fetch (package:just_audio/just_audio.dart:2891)\n<asynchronous suspension>\n": {
    "Exception: HTTP Status Error: 403 => _Exception": 16
  },
  "": {
    "PlatformException(0, Source error, null, null) => PlatformException": 1
  }
}

**Comment by MSOB7YY** [comment]
#265
