### ISSUE TITLE
[BUG] Thumbnails disappearing 

### ISSUE THREAD

**Issue by endless-stupidity** [namidaco/namida#414]
I noticed *none* of my songs had a cover image. The images are there when editing tags but they are not shown in the app or in the notification.

## Expected Behavior
Album images staying there and not disappearing into oblivion every time I open the app.

## Current Behavior
Freaky! In all seriousness, the images reappear (except for one or two albums and I have no idea why only those specifically) when I turn on "Use media store", and in fact, they stay there even if I turn that option off; that is until I close the app and reopen it. Reopening the app with the media store option enabled seems to keep the covers.

Also, with auto coloring on, the colors in the app change for each album even when the image is not shown.

## Steps to Reproduce

1. Open the app, images gone.
2. Use media store and thry reappear 
3. Turn off media store and the don't disappear 
4. Reopen the app, they're gone 😔

## Screenshots

![IMG_20241201_095836](https://github.com/user-attachments/assets/f80dd36c-7994-4bd8-b43d-7799d296170f)
![IMG_20241201_095853](https://github.com/user-attachments/assets/8df39e3d-890d-404e-ab84-06c83f806148)

## Logs

```

`{
  "android": {
    "product": "veux_global",
    "supportedAbis": [
      "arm64-v8a",
      "armeabi-v7a",
      "armeabi"
    ],
    "serialNumber": "unknown",
    "display": "TKQ1.221114.001 test-keys",
    "type": "user",
    "isPhysicalDevice": true,
    "version": {
      "baseOS": "",
      "securityPatch": "2024-10-01",
      "sdkInt": 33,
      "release": "13",
      "codename": "REL",
      "previewSdkInt": 0,
      "incremental": "V816.0.9.0.TKCMIXM"
    },
    "manufacturer": "Xiaomi",
    "tags": "release-keys",
    "bootloader": "unknown",
    "fingerprint": "Redmi/veux_global/veux:13/TKQ1.221114.001/V816.0.9.0.TKCMIXM:user/release-keys",
    "host": "pangu-build-component-system-250311-w3lsl-mxbc7-3hkkg",
    "isLowRamDevice": false,
    "model": "2201116SG",
    "id": "TKQ1.221114.001",
    "brand": "Redmi",
    "device": "veux",
    "board": "veux",
    "hardware": "qcom"
  },
  "package": {
    "appName": "Namida",
    "buildNumber": "241122183",
    "packageName": "com.msob7y.namida",
    "version": "4.7.2",
    "buildSignature": "CB8C070CBDB5E2350ACBAC4DDB1A9DEE89816ECDAFD116D41EFFC14890D98E1C",
    "installerStore": "dev.imranr.obtainium"
  }
}
===============================

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ MissingPluginException(No implementation found for method cancel on channel faudiotagger/stream/1732543179728648)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
│ #1   <asynchronous suspension>
│ #2   EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:688)
│ #3   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ 
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ MissingPluginException(No implementation found for method cancel on channel faudiotagger/stream/1732543179729995)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
│ #1   <asynchronous suspension>
│ #2   EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:688)
│ #3   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ 
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ MissingPluginException(No implementation found for method cancel on channel namida_events)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
│ #1   <asynchronous suspension>
│ #2   EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:688)
│ #3   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ 
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ MissingPluginException(No implementation found for method cancel on channel faudiotagger/stream/1732968369543962)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
│ #1   <asynchronous suspension>
│ #2   EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:688)
│ #3   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ 
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ MissingPluginException(No implementation found for method cancel on channel faudiotagger/stream/1732968369544925)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
│ #1   <asynchronous suspension>
│ #2   EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:688)
│ #3   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ 
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ MissingPluginException(No implementation found for method cancel on channel faudiotagger/stream/1732968369544570)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
│ #1   <asynchronous suspension>
│ #2   EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:688)
│ #3   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ 
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ MissingPluginException(No implementation found for method cancel on channel faudiotagger/stream/1732968421566670)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
│ #1   <asynchronous suspension>
│ #2   EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:688)
│ #3   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ 
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ MissingPluginException(No implementation found for method cancel on channel faudiotagger/stream/1732968421565981.index)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
│ #1   <asynchronous suspension>
│ #2   EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:688)
│ #3   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ 
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ MissingPluginException(No implementation found for method cancel on channel faudiotagger/stream/1732968421567045)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
│ #1   <asynchronous suspension>
│ #2   EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:688)
│ #3   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ 
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ MissingPluginException(No implementation found for method cancel on channel faudiotagger/stream/1732968512851531)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
│ #1   <asynchronous suspension>
│ #2   EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:688)
│ #3   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ 
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ MissingPluginException(No implementation found for method cancel on channel faudiotagger/stream/1732968512851836)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
│ #1   <asynchronous suspension>
│ #2   EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:688)
│ #3   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ 
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ PathNotFoundException: Cannot open file, path = '/storage/emulated/0/Android/data/com.msob7y.namida/files/Artworks/Into You / Void In Blue.png' (OS Error: No such file or directory, errno = 2)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   _checkForErrorResponse (dart:io/common.dart:55)
│ #1   _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
│ #2   _rootRunUnary (dart:async/zone.dart:1407)
│ #3   <asynchronous suspension>
│ #4   _File.writeAsBytes.<anonymous closure> (dart:io/file_impl.dart:634)
│ #5   <asynchronous suspension>
│ #6   Indexer.getArtwork (package:namida/controller/indexer_controller.dart:187)
│ #7   <asynchronous suspension>
│ #8   _ArtworkWidgetState._extractArtwork.<anonymous closure> (package:namida/ui/widgets/artwork.dart:126)
│ #9   <asynchronous suspension>
│ #10   _ArtworkWidgetState._extractArtwork (package:namida/ui/widgets/artwork.dart:118)
│ #11   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ PathNotFoundException
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ PathNotFoundException: Cannot open file, path = '/storage/emulated/0/Android/data/com.msob7y.namida/files/Artworks/Into You / Void In Blue.png' (OS Error: No such file or directory, errno = 2)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   _checkForErrorResponse (dart:io/common.dart:55)
│ #1   _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
│ #2   _rootRunUnary (dart:async/zone.dart:1407)
│ #3   <asynchronous suspension>
│ #4   _File.writeAsBytes.<anonymous closure> (dart:io/file_impl.dart:634)
│ #5   <asynchronous suspension>
│ #6   Indexer.getArtwork (package:namida/controller/indexer_controller.dart:187)
│ #7   <asynchronous suspension>
│ #8   _ArtworkWidgetState._extractArtwork.<anonymous closure> (package:namida/ui/widgets/artwork.dart:126)
│ #9   <asynchronous suspension>
│ #10   _ArtworkWidgetState._extractArtwork (package:namida/ui/widgets/artwork.dart:118)
│ #11   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ PathNotFoundException
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-------------------------------
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ PathNotFoundException: Cannot open file, path = '/storage/emulated/0/Android/data/com.msob7y.namida/files/Artworks/Into You / Void In Blue.png' (OS Error: No such file or directory, errno = 2)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   _checkForErrorResponse (dart:io/common.dart:55)
│ #1   _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
│ #2   _rootRunUnary (dart:async/zone.dart:1407)
│ #3   <asynchronous suspension>
│ #4   _File.writeAsBytes.<anonymous closure> (dart:io/file_impl.dart:634)
│ #5   <asynchronous suspension>
│ #6   Indexer.getArtwork (package:namida/controller/indexer_controller.dart:187)
│ #7   <asynchronous suspension>
│ #8   _ArtworkWidgetState._extractArtwork.<anonymous closure> (package:namida/ui/widgets/artwork.dart:126)
│ #9   <asynchronous suspension>
│ #10   _ArtworkWidgetState._extractArtwork (package:namida/ui/widgets/artwork.dart:118)
│ #11   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ PathNotFoundException
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

## Possible Solution

Zero ideas lol.

**Comment by endless-stupidity** [comment]
Actually, looking at the logs, it seems to be having a problem with the specific album "into you / void in blue". But even this seemingly broken album still has it's cover image when editing tags: 

![IMG_20241201_102135](https://github.com/user-attachments/assets/421ea95d-bb1a-4881-b442-aaef68f83128)

![IMG_20241201_102204](https://github.com/user-attachments/assets/656d6242-844b-40c2-970e-64945c3508fe)

(And yes, all four tracks have the image show up in the tag editor).

Could it be because of the slash (/) in the name, you know, the app mistaking it for a directory or something?

**Comment by MSOB7YY** [comment]
thanks for the detailed report, this was a small bug added lately when "group artworks by album" was enabled, pls update to v4.7.3 or later from here https://github.com/namidaco/namida-snapshots/releases 

> Also, with auto coloring on, the colors in the app change for each album even when the image is not shown.

that might be a bug too let me check again

as for the album "into you / void in blue", yes it mistaken it as a path, i haven't done any convertion for this part as i never thought album name could have this, supporting this means we convert album identifier each time we display it so idk it might affect performance

**Comment by endless-stupidity** [comment]
Yup, updating to the beta and reindexing and clearing the image cache resolved the issue.

Thanks and nice work!

**Comment by MSOB7YY** [comment]
yeyyy thank you!!
