### ISSUE TITLE
[BUG] Crash when opening .m4a files

### ISSUE THREAD

**Issue by Antiwh0re** [namidaco/namida#434]
Regularly when I tap a file in .m4a format encoded with ALAC codec...

## Expected Behavior
...File gets played.

## Current Behavior
...App crashes. On re-opening the same file is played successfully.

## Steps to Reproduce
Above.

## Screenshots
No.

## Logs
Some device data in that log, so no.
But after the device part I see many repeats of this pattern:
│ RangeError (length): Invalid value: Not in inclusive range 0..3722: 3723
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   _Array.[] (dart:core-patch/array.dart)
│ #1   _CastListBase.[] (dart:_internal/cast.dart:99)
│ #2   DEListieSizie.changeListSize (package:dart_extensions/src/list_extensions.dart:394)
│ #3   WaveformController._downscaledWaveformLists.<anonymous closure> (package:namida/controller/waveform_controller.dart:98)
│ #4   DEListieExt.loop (package:dart_extensions/src/list_extensions.dart:20)
│ #5   WaveformController._downscaledWaveformLists (package:namida/controller/waveform_controller.dart:97)
│ #6   compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:19)
│ #7   _RemoteRunner._run (dart:isolate:1090)
│ #8   _RemoteRunner._remoteExecute (dart:isolate:1084)
│ #9   _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300)
│ #10   _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ RangeError
I guess it's related to waveform bug we've discussed recently.

## Possible Solution
?

**Comment by MSOB7YY** [comment]
that waveform bug is already fixed, but i dont think that was the problem.
its hard to debug decoder issues crashes, anyways in future i will update ffmpeg decoders so this might help

**Comment by Antiwh0re** [comment]
I thought of waveform bug because of this WaveformController in the stack trace.
As for the current issue, it seems to me it's not the decoder issue, because it happens only when you'd played some tracks before the .m4a track. If you fresh start a player and then play this file, it plays fine (and continues to play fine for subsequent .m4a tracks). This implies that the bug arises because of the player's inner state, which is different for these two cases.

**Comment by Antiwh0re** [comment]
Fallback decoder? I thought it was the one and only. Which is the main one then?

**Comment by MSOB7YY** [comment]
the default is system decoders (hardware), or whatever exoplayer uses. this can be equivalent to "hw" in mxplayer for example (not hw+ nor sw)

**Comment by Antiwh0re** [comment]
So this exoplayer does the actual decoding?

**Comment by MSOB7YY** [comment]
might or might not. im not so experienced with this

**Comment by MSOB7YY** [comment]
check if it happens on 5.0.1 https://github.com/namidaco/namida-snapshots/releases

**Comment by MSOB7YY** [comment]
@Antiwh0re can u check if it happens on v5.0.4 or not? https://github.com/namidaco/namida/releases

**Comment by Antiwh0re** [comment]
I haven't visited Github for a while, so didn't answer. I've downloaded 5.0.5 and the crashes are still here. If I play an mp3 file first and play an m4a file after that, it crashes.

**Comment by MSOB7YY** [comment]
sorry for not noticing, the issue is tracked now at #698
it should be solved when amplituda fixes it (https://github.com/lincollincol/Amplituda/issues/90)

**Comment by MSOB7YY** [comment]
fixed for sure in v5.4.7 https://github.com/namidaco/namida-snapshots/releases
